# Use an official Node.js image
FROM node:20

# Set the working directory to /app
WORKDIR /app/ardeux_core

# Copy package.json and package-lock.json to the container
COPY ardeux_core/package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code
COPY ardeux_core/ .

# Expose port 3000 for Node.js app
EXPOSE 3000

# Define the command to run the Node.js app
CMD ["node", "index.js"]
